USE DINGDONGPHOTOGRAPHY;

INSERT INTO SERVICE_PACKAGE VALUES (1, "P4HR");
INSERT INTO SERVICE_PACKAGE VALUES (1, "STUD");
INSERT INTO SERVICE_PACKAGE VALUES (1, "10PR");
INSERT INTO SERVICE_PACKAGE VALUES (1, "HOST");
INSERT INTO SERVICE_PACKAGE VALUES (1, "PRNT");
INSERT INTO SERVICE_PACKAGE VALUES (1, "ZIPF");
INSERT INTO SERVICE_PACKAGE VALUES (1, "PREP");
INSERT INTO SERVICE_PACKAGE VALUES (1, "EDIT");
INSERT INTO SERVICE_PACKAGE VALUES (1, "TRVL");

INSERT INTO SERVICE_PACKAGE VALUES (2, "P3HR");
INSERT INTO SERVICE_PACKAGE VALUES (2, "STUD");
INSERT INTO SERVICE_PACKAGE VALUES (2, "10PR");
INSERT INTO SERVICE_PACKAGE VALUES (2, "HOST");
INSERT INTO SERVICE_PACKAGE VALUES (2, "PRNT");
INSERT INTO SERVICE_PACKAGE VALUES (2, "ZIPF");
INSERT INTO SERVICE_PACKAGE VALUES (2, "PREP");
INSERT INTO SERVICE_PACKAGE VALUES (2, "EDIT");
INSERT INTO SERVICE_PACKAGE VALUES (2, "TRVL");

INSERT INTO SERVICE_PACKAGE VALUES (3, "P3HR");
INSERT INTO SERVICE_PACKAGE VALUES (3, "10PR");
INSERT INTO SERVICE_PACKAGE VALUES (3, "HOST");
INSERT INTO SERVICE_PACKAGE VALUES (3, "PRNT");
INSERT INTO SERVICE_PACKAGE VALUES (3, "ZIPF");
INSERT INTO SERVICE_PACKAGE VALUES (3, "PREP");
INSERT INTO SERVICE_PACKAGE VALUES (3, "EDIT");
INSERT INTO SERVICE_PACKAGE VALUES (3, "TRVL");


SELECT PKG.PackageName, PKG.PackageDesc, PKG.Cost, SVC.ServiceDesc, SVC.Cost
FROM SERVICE_PACKAGE SP
INNER JOIN PACKAGE PKG
ON SP.PackageID = PKG.PackageID
INNER JOIN SERVICE SVC
ON SP.ServiceCode = SVC.ServiceCode;