USE DINGDONGPHOTOGRAPHY;

INSERT INTO EVENT_TYPE VALUES ("BDAY", "Birthday");
INSERT INTO EVENT_TYPE VALUES ("WEDD", "Wedding");
INSERT INTO EVENT_TYPE VALUES ("FRML", "Formal");
INSERT INTO EVENT_TYPE VALUES ("OTHR", "Other");

SELECT * FROM EVENT_TYPE;